server:
  port: 8088
spring:
  application:
    name: api-gateway
  cloud:
    #gateway配置
    gateway:
      #路由规则
      routes:
        - id: order_route  #路由的唯一标识 路由到订单
          uri: lb://order-service  #需要转发的地址lb 使用nacos中本地负载均衡策略
          #断言规则 用于路由规则的匹配
          predicates:
            - Path=/order/**
            #http://localhost:8088/order-serv/order/add路由到
            #http://localhost:8020/order-serv/order/add
          #  - After=2019-12-31T23:59:59.789+08:00[Asia/Shanghai]
          #  - Header=X-Request-Id,\d+
          #  - Method=Get
          #  - Query=name
            - CheckAuth=xushu
          #filters:
          #  - StripPrefix=1 #内置过滤器 转发之前去掉第一层路径
            #http://localhost:8020/order/add
      #跨域配置
      globalcors:
        cors-configurations:
          '[/**]': #允许跨域访问的资源
            allowedOrigins: "*" #跨域允许来源
            allowedMethods:
              - GET
              - POST

    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
    #配置sentinel
#    sentinel:
#      transport:
#        dashboard:
#          127.0.0.1:8858
#      scg:
#        fallback:
#          mode: response
#          response-body: "{code:'',message:''}"
